development:
  domain: musick.localhost:3000
  ga_id: 'UA-XXXXXX-XX'
  amazon_associate_tag: 'musick0f-22'
  hash_tag: '#xtxexsxt'
  comment_count: 2
  need_invitation: true
test:
  domain: test.host
  ga_id: 'UA-XXXXXX-XX'
  amazon_associate_tag: 'musick0f-22'
  hash_tag: '#musick'
  comment_count: 2
  need_invitation: true
staging:
  domain: musick-dev.herokuapp.com
  a_id: 'UA-XXXXXX-XX'
  amazon_associate_tag: 'musick0f-22'
  hash_tag: '#musick'
  comment_count: 2
  need_invitation: true
production:
  domain: musick.info
  ga_id: 'UA-25643488-1'
  amazon_associate_tag: 'musick0f-22'
  hash_tag: '#musick'
  comment_count: 2
  need_invitation: true