development:
  domain: musick.localhost:3000
  ga_id: 'UA-XXXXXX-XX'
  hash_tag: '#xtxexsxt'

test:
  domain: test.host
  ga_id: 'UA-XXXXXX-XX'
  hash_tag: '#musick'
  
staging:
  domain: musick-dev.herokuapp.com
  a_id: 'UA-XXXXXX-XX'
  hash_tag: '#musick'
  
production:
  domain: musick.info
  ga_id: 'UA-25643488-1'
  hash_tag: '#musick'
